[versions]
exposed-version = "0.61.0"
h2-version = "2.3.232"
kotlin-version = "2.1.21"
ktor-version = "3.1.3"
logback-version = "1.5.18"
hikaricp-version = "6.3.0"
postgresql-version = "42.7.5"
liquibase-version = "4.31.1"
thymeleaf-layout-dialect-version = "3.4.0"
jsoup-version = "1.20.1"
mockk-version = "1.14.2"

[libraries]
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-version" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor-version" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-version" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed-version" }
exposed-javatime = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed-version" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed-version" }
h2 = { module = "com.h2database:h2", version.ref = "h2-version" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp-version" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql-version" }
liquibase = { module = "org.liquibase:liquibase-core", version.ref = "liquibase-version" }
thymeleaf-layout-dialect = { module = "nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect", version.ref = "thymeleaf-layout-dialect-version" }
ktor-server-thymeleaf = { module = "io.ktor:ktor-server-thymeleaf", version.ref = "ktor-version" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup-version" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor-version" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
